[theme]
base = "dark"
primaryColor = "#e2a63b"
backgroundColor = "#171817"
secondaryBackgroundColor = "#24241f"
textColor = "#e8e3d7"
font = "sans serif"

[server]
maxUploadSize = 100
headless = true

[browser]
gatherUsageStats = false
